package com.tyxapp.bangumi_jetpack.player

const val FULL_SCREEN_KEY = "FULL_SCREEN_KEY"
const val FULL_SCREEN_CODE = 0

const val DATA_SOURCE_KEY = "DATA_SOURCE_KEY"

const val SPEED_CONTROL_KEY = "SPEED_CONTROL_KEY"
const val SPEED_CONTROL_CODE = 2

const val REFRESH_VIDEO_CODE = 1

const val STATE_BAR_KEY = "STATE_BAR_KEY"
const val STATE_BAR_CODE = 3

const val UPDATE_SEEK_KEY = "UPDATE_SEEK_KEY"
const val UPDATE_SEEK_CODE = 4

const val SHOW_DANMU_SETTING_CODE = 5

const val ERROR_COVER_VISIBLE_CODE = 6
const val ERROR_COVER_VISIBLE_KEY = "ERROR_COVER_VISIBLE_KEY"

const val PERMISSION_REQUEST_CODE = 7
const val PERMISSION_REQUEST_KEY = "PERMISSION_REQUEST_KEY"

const val LOCAL_VIDEO_URL_KEY = "LOCAL_VIDEO_URL_KEY"

const val FOLLOW_RESULT_KEY = "FOLLOW_RESULT_KEY"